$(document).ready(function(){
  $("#questionjs").click(function(){
    $("#ansjs").fadeToggle(1000);
  });
  $("#questionop").click(function(){
    $("#ansop").slideToggle(1000);
  });
  $("#questionvar").click(function(){
    $("#ansvar").fadeToggle();
  });
  $("#questionvarna").click(function(){
    $("#ansvarna").slideToggle();
  });
  $("#questionfn").click(function(){
    $("#ansfn").fadeToggle(1000);
  });
  $("#questionstr").click(function(){
    $("#ansstr").fadeToggle(1000);
  });
  $("#questionmet").click(function(){
    $("#ansemet").fadeToggle(1000);
  });
  $("#questionarg").click(function(){
    $("#ansarg").fadeToggle(1000);
  });
  $("#questionpar").click(function(){
    $("#anspar").fadeToggle(1000);
  });
  $("#questionret").click(function(){
    $("#ansret").fadeToggle(1000);
  });
  $("#questioncha").click(function(){
    $("#anscha").fadeToggle(1000);
  });
  $("#questionstrque").click(function(){
    $("#ansstrque").fadeToggle(1000);
  });
  $("#questionboo").click(function(){
    $("#ansboo").fadeToggle(1000);
  });
  $("#questionundef").click(function(){
    $("#ansundef").fadeToggle(1000);
  });
  $("#questionesc").click(function(){
    $("#ansesc").fadeToggle(1000);
  });
  $("#questioncomt").click(function(){
    $("#anscomt").fadeToggle(1000);
  });
  $("#questionjq").click(function(){
    $("#ansjq").fadeToggle(1000);
  });
  $("#questionattr").click(function(){
    $("#ansattr").fadeToggle(1000);
  });
  $("#questionalert").click(function(){
    $("#ansalert").fadeToggle(1000);
  });
  $("#questionnan").click(function(){
    $("#ansnan").fadeToggle(1000);
  });
});
